# Generated by Django 5.0.7 on 2024-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficial',
            name='numero_identificatorio',
            field=models.CharField(default='DESCONOCIDO', max_length=20, unique=True),
        ),
    ]
