# Generated by Django 5.0.7 on 2024-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa_del_patente',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
