# Generated by Django 5.0.7 on 2024-08-06 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraccion', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infracion',
            new_name='Infraccion',
        ),
    ]
